# scheme = tokyonight
palette = "tokyonight"

[palettes.tokyonight]
fg = "#c0caf5"
muted = "#414868"
primary = "#7aa2f7"
secondary = "#bb9af7"
accent = "#e0af68"
success = "#73daca"
warning = "#ff9e64"
error = "#f7768e"
symbol = "#7dcfff"

[container]
disabled = true

[directory]
style = "fg:primary"

[git_branch]
style = "fg:secondary"

[git_status]
style = "fg:accent"

[python]
style = "fg:success"

[nodejs]
style = "fg:success"

[rust]
style = "fg:success"

[cmd_duration]
style = "fg:warning"

[character]
success_symbol = "[❯](fg:symbol)"
error_symbol = "[❯](fg:error)"
vicmd_symbol = "[❮](fg:primary)"
