# scheme = everforest-dark
palette = "everforest"

[palettes.everforest]
fg = "#d3c6aa"
muted = "#4a555b"
primary = "#83c092"
secondary = "#d699b6"
accent = "#dbbc7f"
success = "#a7c080"
warning = "#e69875"
error = "#e67e80"
symbol = "#7fbbb3"

[container]
disabled = true

[directory]
style = "fg:primary"

[git_branch]
style = "fg:secondary"

[git_status]
style = "fg:accent"

[python]
style = "fg:success"

[nodejs]
style = "fg:success"

[rust]
style = "fg:success"

[cmd_duration]
style = "fg:warning"

[character]
success_symbol = "[❯](fg:symbol)"
error_symbol = "[❯](fg:error)"
vicmd_symbol = "[❮](fg:primary)"
