# scheme = nord
palette = "nord"

[palettes.nord]
fg = "#d8dee9"
muted = "#4c566a"
primary = "#81a1c1"
secondary = "#b48ead"
accent = "#ebcb8b"
success = "#a3be8c"
warning = "#d08770"
error = "#bf616a"

[container]
disabled = true

[directory]
style = "fg:primary"

[git_branch]
style = "fg:secondary"

[git_status]
style = "fg:accent"

[python]
style = "fg:success"

[nodejs]
style = "fg:success"

[rust]
style = "fg:success"

[cmd_duration]
style = "fg:warning"

[character]
success_symbol = "[❯](fg:success)"
error_symbol = "[❯](fg:error)"
vicmd_symbol = "[❮](fg:primary)"
